### ISSUE TITLE
app 启动后报错

### ISSUE THREAD

**Issue by 13121349269** [KubeLilin/kubelilin#42]
KubeLilin is starting......
                                       ##         .
                                 ## ## ##        ==
                              ## ## ## ## ##    ===
                           /""""""""""""""""\___/ ===
                      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
                           \______ o          _,/
                            \      \       _,'
                              '--.._\..--''         KubeLilin An Cloud-Native application platform for Kubernetes.

2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] config_dev.yml
2024/08/30 17:10:25.98 - [YOYOGO] - [INFO] mvc.template:  v1/{controller}/{action}
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] loaded health endpoint. class=Endpoint host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] loaded health-readiness endpoint. class=Endpoint host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] loaded health endpoint. class=Endpoint host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] loaded prometheus endpoint. class=Endpoint host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] loaded graphViz endpoint. class=Endpoint host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] loaded router information endpoint. class=Endpoint host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] loaded jwt endpoint. class=Endpoint host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [democontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [tenantcontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [sysmenucontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [usercontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [tenantrolecontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [tenantuserrolecontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [rolemenucontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [clustercontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [applicationcontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [deploymentcontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [podcontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [metricscontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [serviceconnectioncontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [servicecontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [devopscontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [apigatewaycontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [configmapcontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [dynamiccontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [runtimecontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [pipelinecontroller] class=ControllerBuilder host=1b9dc35b07c9
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [deliverablescontroller] class=ControllerBuilder host=1b9dc35b07c9
panic: *controllers.DeliverablesController[deliverablescontroller]: dependency *deliverables.TenantDeliverablesTreeService not exists in container

goroutine 1 [running]:
github.com/yoyofxteam/dependencyinjection/di.panicf(...)
        /home/runner/go/pkg/mod/github.com/yoyofxteam/dependencyinjection@v1.0.1/di/panic.go:6
github.com/yoyofxteam/dependencyinjection/di.(*Container).registerProviderParameters(0xc0001aac90, {0x234a780, 0xc0003706f0})
        /home/runner/go/pkg/mod/github.com/yoyofxteam/dependencyinjection@v1.0.1/di/container.go:176 +0x5b4
github.com/yoyofxteam/dependencyinjection/di.(*Container).Compile(0xc0001aac90)
        /home/runner/go/pkg/mod/github.com/yoyofxteam/dependencyinjection@v1.0.1/di/container.go:77 +0x1fd
github.com/yoyofxteam/dependencyinjection.(*Container).compile(0xc0001552a0?)
        /home/runner/go/pkg/mod/github.com/yoyofxteam/dependencyinjection@v1.0.1/container.go:58 +0x4c
github.com/yoyofxteam/dependencyinjection.New({0xc0001ac000, 0x40, 0xc000155260?})
        /home/runner/go/pkg/mod/github.com/yoyofxteam/dependencyinjection@v1.0.1/container.go:16 +0x268
github.com/yoyofxteam/dependencyinjection.ServiceCollection.Build({{0xc0000bee00?, 0x1c53d40?, 0x2149f10?}, 0xc0002d5560?})
        /home/runner/go/pkg/mod/github.com/yoyofxteam/dependencyinjection@v1.0.1/default_serviceprovider_factory.go:23 +0x49b
github.com/yoyofx/yoyogo/abstractions.(*HostBuilder).Build(0xc000569f10)
        /home/runner/go/pkg/mod/github.com/yoyofx/yoyogo@v1.8.4/abstractions/hostbuilder.go:179 +0x296
main.main()
        /home/runner/work/kubelilin/kubelilin/src/main.go:31 +0x3cf

**Comment by yoyofx** [comment]
把这部分代码注释掉就可以了
```
2024/08/30 17:10:25.98 - [YOYOGO] - [DEBUG] add mvc controller: [deliverablescontroller] class=ControllerBuilder host=1b9dc35b07c9
panic: *controllers.DeliverablesController[deliverablescontroller]: dependency *deliverables.TenantDeliverablesTreeService not exists in container
```

**Comment by yoyofx** [comment]
已修复
